// GENERATED by scripts/photo-variants.mjs — do not edit by hand.
// Re-run `npm run optimize-photos` (or `npm run photo-variants`) after adding photos.

export interface PhotoMeta {
  /** intrinsic width of the source file */
  w: number;
  /** intrinsic height of the source file */
  h: number;
  /** widths available: generated variants, ascending, ending with the source width */
  widths: number[];
}

export const PHOTO_MANIFEST: Record<string, PhotoMeta> = {
  "/photos/as-found/20250708_173939.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/as-found/20250708_173953.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/as-found/511550695_705881208746655_7654873925645486782_n.jpg": {
    "w": 960,
    "h": 720,
    "widths": [
      480,
      960
    ]
  },
  "/photos/as-found/511691016_727930883073436_2255052552686165886_n.jpg": {
    "w": 960,
    "h": 720,
    "widths": [
      480,
      960
    ]
  },
  "/photos/as-found/511853656_726849399726159_726664144942546534_n.jpg": {
    "w": 960,
    "h": 720,
    "widths": [
      480,
      960
    ]
  },
  "/photos/as-found/512014606_1421811542282879_4787133338647080129_n.jpg": {
    "w": 960,
    "h": 720,
    "widths": [
      480,
      960
    ]
  },
  "/photos/as-found/512111523_998182165724339_3908359442190371356_n.jpg": {
    "w": 960,
    "h": 720,
    "widths": [
      480,
      960
    ]
  },
  "/photos/as-found/512562778_1253709202951492_3420004356951000960_n.jpg": {
    "w": 960,
    "h": 720,
    "widths": [
      480,
      960
    ]
  },
  "/photos/as-found/512574166_1247098590212931_8903988289943527610_n.jpg": {
    "w": 960,
    "h": 720,
    "widths": [
      480,
      960
    ]
  },
  "/photos/factory/1990-cr125r-factory.jpg": {
    "w": 915,
    "h": 562,
    "widths": [
      480,
      915
    ]
  },
  "/photos/finished/20250821_153620.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/20250823_112313.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/20250823_145657.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/20251018_135845.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/banner.jpg": {
    "w": 2560,
    "h": 1183,
    "widths": [
      480,
      1000,
      2560
    ]
  },
  "/photos/finished/detail-cockpit.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/detail-engine-hpp.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/detail-engine-pipe.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/detail-seat-pipe.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/detail-shroud-left.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/front-on.jpg": {
    "w": 924,
    "h": 2000,
    "widths": [
      480,
      924
    ]
  },
  "/photos/finished/IMG_0372.jpeg": {
    "w": 2000,
    "h": 1500,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/profile-chain-side.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/profile-pipe-side.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/rear-on.jpg": {
    "w": 924,
    "h": 2000,
    "widths": [
      480,
      924
    ]
  },
  "/photos/finished/three-quarter-front.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/finished/three-quarter-rear.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/MXA/Retro_1_e-scaled.jpg": {
    "w": 2048,
    "h": 1388,
    "widths": [
      480,
      1000,
      2048
    ]
  },
  "/photos/MXA/Retro_2_e-1170x1536.jpeg": {
    "w": 1170,
    "h": 1536,
    "widths": [
      480,
      1000,
      1170
    ]
  },
  "/photos/MXA/Retro_4_e-scaled.jpg": {
    "w": 1388,
    "h": 2048,
    "widths": [
      480,
      1000,
      1388
    ]
  },
  "/photos/MXA/Retro_5_e-1148x1536.jpeg": {
    "w": 1148,
    "h": 1536,
    "widths": [
      480,
      1000,
      1148
    ]
  },
  "/photos/MXA/Retro_7_e-scaled.jpg": {
    "w": 2048,
    "h": 1366,
    "widths": [
      480,
      1000,
      2048
    ]
  },
  "/photos/MXA/Retro_8_e-scaled.jpg": {
    "w": 1357,
    "h": 2048,
    "widths": [
      480,
      1000,
      1357
    ]
  },
  "/photos/restoration/20250712_163005.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/restoration/20250719_140016.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/restoration/20250719_191631.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/restoration/20250719_191637.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/restoration/20250727_180742.jpg": {
    "w": 2000,
    "h": 924,
    "widths": [
      480,
      1000,
      2000
    ]
  },
  "/photos/restoration/pipe-refinished-detail.jpg": {
    "w": 924,
    "h": 2000,
    "widths": [
      480,
      924
    ]
  },
  "/photos/restoration/pipe-refinished.jpg": {
    "w": 924,
    "h": 2000,
    "widths": [
      480,
      924
    ]
  },
  "/photos/restoration/sprockets.jpg": {
    "w": 924,
    "h": 2000,
    "widths": [
      480,
      924
    ]
  },
  "/photos/restoration/tires-dunlop.jpg": {
    "w": 924,
    "h": 2000,
    "widths": [
      480,
      924
    ]
  }
};
